openapi: 3.1.0
info:
  title: Test
  version: 1.0.0

components:
  schemas:
    main:
      "$id": example.schema.json
      "$schema": https://json-schema.org/draft/2020-12/schema
      description: A representation of a person, company, organization, or place
      type: object
      properties:
        fruits:
          type: array
          items:
            type: string
        vegetables:
          type: array
          items:
            "$ref": "#/components/schemas/veggie"
    veggie:
      type: object
      required:
      - veggieName
      - veggieLike
      properties:
        veggieName:
          type: string
          description: The name of the vegetable.
        veggieLike:
          type: boolean
          description: Do I like this vegetable?